# Database Connection
spring.datasource.url=jdbc:sqlite:movies.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate Configuration
# 'update' is fine for development, 'none' or 'validate' is preferred for production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# SQLite Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Clean Logging
logging.level.root=INFO
logging.level.com.example.moviebot=INFO
logging.level.org.hibernate=ERROR

bot.token=8382222647:AAEBtZMasqmb_MZMjYEW74aJXBv25g4YQFg